fix: compilation error due to redefined define
Fix the following compilation error:
<path>\openthread-core-cc13xx_cc26xx-config.h:82: error:
"OPENTHREAD_CONFIG_PING_SENDER_ENABLE" redefined
   82 | #define OPENTHREAD_CONFIG_PING_SENDER_ENABLE 1

[VAIL-13496]